ci: Reorganize the jobs for consistency

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -25,46 +25,7 @@ default:
   tags:
     - CI-gateway
 
-mesa-trigger-container:
-  stage: containers
-  extends: .fdo.container-build@debian
-  before_script:
-    # Getting this on the farm runner gateways,
-    #   User-selected graph driver \"vfs\" overwritten by graph driver \"overlay\" from database - delete libpod local files to resolve"
-    - rm -rf /var/lib/containers/storage/libpod/*
-  rules:
-    - changes:
-      - .gitlab-ci.yml
-      - executor/client/**/*
-      - valvetraces/**/*
-      - .gitlab-ci/${CI_JOB_NAME}.sh
-  variables:
-    FDO_DISTRIBUTION_PACKAGES: 'python3 python3-pip wget findutils bash'
-    FDO_REPO_SUFFIX: 'mesa-trigger'
-    FDO_DISTRIBUTION_TAG: '2022-02-14.1'
-    FDO_DISTRIBUTION_VERSION: 'testing'
-    FDO_DISTRIBUTION_EXEC: .gitlab-ci/${CI_JOB_NAME}.sh
-
-mesa-downstream-trigger-container:
-  stage: containers
-  extends: .fdo.container-build@debian
-  before_script:
-    # Getting this on the farm runner gateways,
-    #   User-selected graph driver \"vfs\" overwritten by graph driver \"overlay\" from database - delete libpod local files to resolve"
-    - rm -rf /var/lib/containers/storage/libpod/*
-  rules:
-    - changes:
-      - containers/gitlab-trigger/**/*
-      - executor/client/**/*
-      - valvetraces/**/*
-      - .gitlab-ci.yml
-      - .gitlab-ci/${CI_JOB_NAME}.sh
-  variables:
-    FDO_DISTRIBUTION_PACKAGES: 'bash inotify-tools git python3-pip python3-jinja2 skopeo wget findutils'
-    FDO_REPO_SUFFIX: 'mesa-downstream-trigger'
-    FDO_DISTRIBUTION_TAG: '2022-02-14.1'
-    FDO_DISTRIBUTION_VERSION: 'testing'
-    FDO_DISTRIBUTION_EXEC: .gitlab-ci/${CI_JOB_NAME}.sh
+#### BOOTSTRAP CONTAINERS ####
 
 python-container:
   stage: prep
@@ -181,7 +142,10 @@ valve-infra-base-container:
     sleep 2
     podman push $IMAGE_NAME
   rules:
-    - when: on_success
+    - changes:
+      - .gitlab-ci.yml
+
+#### TESTS ####
 
 test ansible:
   # Minimal image for running podman and friends
@@ -221,73 +185,22 @@ test ansible:
     - changes:
       # We might want to trigger on executor and salad...
       - ansible/**/*
-
-valve-infra-container:
-  # Minimal image for running podman and friends
-  image: registry.freedesktop.org/freedesktop/ci-templates/x86_64/container-build-base:2021-06-21.2
-  stage: deploy
-  variables:
-    BASE_CONTAINER_TAG: !reference [valve-infra-base-container, variables, FDO_DISTRIBUTION_TAG]
-    BASE_IMAGE: $CI_REGISTRY_IMAGE/valve-infra-base-container:$BASE_CONTAINER_TAG
-    FDO_DISTRIBUTION_TAG: 2022-02-10.1
-    IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_JOB_NAME:$FDO_DISTRIBUTION_TAG
-  before_script:
-    # Getting this on the farm runner gateways,
-    #   User-selected graph driver \"vfs\" overwritten by graph driver \"overlay\" from database - delete libpod local files to resolve"
-    - rm -rf /var/lib/containers/storage/libpod/*
-  script: |
-    set -x
-
-    ( skopeo inspect docker://$IMAGE_NAME || true ) | jq '[.Digest, .Layers]' > local_sha
-    if [ -s local_sha ]; then
-       echo "Container already built"
-       exit 0
-    fi
-
-    sh .gitlab-ci/valve-infra-container-build.sh
-  rules:
-    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
-      when: on_success
-
-machine-registration:
-  # Minimal image for running podman and friends
-  image: registry.freedesktop.org/freedesktop/ci-templates/x86_64/container-build-base:2021-06-21.2
-  stage: deploy
-  variables:
-    FDO_DISTRIBUTION_TAG: 2022-02-10.1
-    IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_JOB_NAME:$FDO_DISTRIBUTION_TAG
-  before_script:
-    # Getting this on the farm runner gateways,
-    #   User-selected graph driver \"vfs\" overwritten by graph driver \"overlay\" from database - delete libpod local files to resolve"
-    - rm -rf /var/lib/containers/storage/libpod/*
-  script: |
-    set -x
-
-    ( skopeo inspect docker://$IMAGE_NAME || true ) | jq '[.Digest, .Layers]' > local_sha
-    if [ -s local_sha ]; then
-       echo "Container already built"
-       exit 0
-    fi
-
-    sh .gitlab-ci/machine-registration-container-build.sh
-  variables:
-    IMAGE_NAME: registry.freedesktop.org/mupuf/valve-infra/machine_registration
-
-
+      - executor/**/*
+      - salad/**/*
 
 # FIXME: ipxe-boot-server should be moved to a proper Python package,
 # so it can follow the pattern of the other Python services regarding
 # linting, testing and building.
-ipxe-boot-server:
+test ipxe-boot-server:
   extends:
     - .set-python-image
   stage: tests
   rules:
     - changes:
-      - $CI_JOB_NAME/**/*
+      - ipxe-boot-server/**/*
       - .gitlab-ci.yml
   script:
-    - cd $CI_JOB_NAME
+    - cd ipxe-boot-server/
     # Shouldn't we just use the setup.py to launch this, rather than calling specific tools?
     - pycodestyle --max-line-length=120 .
     - pip3 install -r requirements.txt
@@ -308,21 +221,6 @@ ipxe-boot-server:
   artifacts:
     paths:
       - ${PACKAGE_DIR}/dist/
-
-.python-deploy:
-  extends:
-    - .set-python-image
-  stage: deploy
-  rules:
-    - if: $TWINE_PASSWORD == ""
-      when: never
-    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
-      when: on_success
-  script:
-    - twine upload -u "__token__" ${PACKAGE_DIR}/dist/*
-  # This will fail if the package already exists, not pleasant to
-  # check ahead of time for that, so allow the job to fail
-  allow_failure: true
 
 test executor/client:
   extends:
@@ -359,6 +257,112 @@ test salad:
     - .python-test
   variables:
     PACKAGE_DIR: 'salad'
+
+#### PUBLIC CONTAINERS ####
+
+mesa-trigger-container:
+  stage: containers
+  extends: .fdo.container-build@debian
+  before_script:
+    # Getting this on the farm runner gateways,
+    #   User-selected graph driver \"vfs\" overwritten by graph driver \"overlay\" from database - delete libpod local files to resolve"
+    - rm -rf /var/lib/containers/storage/libpod/*
+  variables:
+    FDO_DISTRIBUTION_PACKAGES: 'python3 python3-pip wget findutils bash'
+    FDO_REPO_SUFFIX: 'mesa-trigger'
+    FDO_DISTRIBUTION_TAG: '2022-02-14.1'
+    FDO_DISTRIBUTION_VERSION: 'testing'
+    FDO_DISTRIBUTION_EXEC: .gitlab-ci/${CI_JOB_NAME}.sh
+  rules:
+    - changes:
+      - .gitlab-ci.yml
+
+mesa-downstream-trigger-container:
+  stage: containers
+  extends: .fdo.container-build@debian
+  before_script:
+    # Getting this on the farm runner gateways,
+    #   User-selected graph driver \"vfs\" overwritten by graph driver \"overlay\" from database - delete libpod local files to resolve"
+    - rm -rf /var/lib/containers/storage/libpod/*
+  variables:
+    FDO_DISTRIBUTION_PACKAGES: 'bash inotify-tools git python3-pip python3-jinja2 skopeo wget findutils'
+    FDO_REPO_SUFFIX: 'mesa-downstream-trigger'
+    FDO_DISTRIBUTION_TAG: '2022-02-14.1'
+    FDO_DISTRIBUTION_VERSION: 'testing'
+    FDO_DISTRIBUTION_EXEC: .gitlab-ci/${CI_JOB_NAME}.sh
+  rules:
+    - changes:
+      - .gitlab-ci.yml
+
+valve-infra-container:
+  # Minimal image for running podman and friends
+  image: registry.freedesktop.org/freedesktop/ci-templates/x86_64/container-build-base:2021-06-21.2
+  stage: containers
+  variables:
+    BASE_CONTAINER_TAG: !reference [valve-infra-base-container, variables, FDO_DISTRIBUTION_TAG]
+    BASE_IMAGE: $CI_REGISTRY_IMAGE/valve-infra-base-container:$BASE_CONTAINER_TAG
+    FDO_DISTRIBUTION_TAG: 2022-02-10.1
+    IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_JOB_NAME:$FDO_DISTRIBUTION_TAG
+  before_script:
+    # Getting this on the farm runner gateways,
+    #   User-selected graph driver \"vfs\" overwritten by graph driver \"overlay\" from database - delete libpod local files to resolve"
+    - rm -rf /var/lib/containers/storage/libpod/*
+  script: |
+    set -x
+
+    ( skopeo inspect docker://$IMAGE_NAME || true ) | jq '[.Digest, .Layers]' > local_sha
+    if [ -s local_sha ]; then
+       echo "Container already built"
+       exit 0
+    fi
+
+    sh .gitlab-ci/valve-infra-container-build.sh
+  rules:
+    - changes:
+      - .gitlab-ci.yml
+
+machine-registration:
+  # Minimal image for running podman and friends
+  image: registry.freedesktop.org/freedesktop/ci-templates/x86_64/container-build-base:2021-06-21.2
+  stage: containers
+  variables:
+    FDO_DISTRIBUTION_TAG: 2022-02-10.1
+    IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_JOB_NAME:$FDO_DISTRIBUTION_TAG
+    TAG_AS_LATEST: 'yes'
+  before_script:
+    # Getting this on the farm runner gateways,
+    #   User-selected graph driver \"vfs\" overwritten by graph driver \"overlay\" from database - delete libpod local files to resolve"
+    - rm -rf /var/lib/containers/storage/libpod/*
+  # FIXME: Move to ci-templates when the entrypoint / working-dir changes are merged into upstream
+  script: |
+    set -x
+
+    ( skopeo inspect docker://$IMAGE_NAME || true ) | jq '[.Digest, .Layers]' > local_sha
+    if [ -s local_sha ]; then
+       echo "Container already built"
+       exit 0
+    fi
+    sh .gitlab-ci/machine-registration-container-build.sh
+  rules:
+    - changes:
+      - .gitlab-ci.yml
+
+#### DEPLOYMENT JOBS ####
+
+.python-deploy:
+  extends:
+    - .set-python-image
+  stage: deploy
+  rules:
+    - if: $TWINE_PASSWORD == ""
+      when: never
+    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
+      when: on_success
+  script:
+    - twine upload -u "__token__" ${PACKAGE_DIR}/dist/*
+  # This will fail if the package already exists, not pleasant to
+  # check ahead of time for that, so allow the job to fail
+  allow_failure: true
 
 deploy executor/client:
   extends:
